#!/usr/bin/env python2
import zmq, msgpack

ctx = zmq.Context()

fetcher = ctx.socket(zmq.SUB)
fetcher.setsockopt(zmq.SUBSCRIBE, "")
fetcher.connect("tcp://127.0.0.1:8998")

while True:
	message = msgpack.unpackb(fetcher.recv())
	print message
