#!/usr/bin/env python2

import zmq, msgpack

ctx = zmq.Context()

collector = ctx.socket(zmq.PULL)
collector.bind("ipc:///tmp/cstatsd")

while True:
	message = msgpack.unpackb(collector.recv())
	print message
